### ISSUE TITLE
Support reading options from a configuration file

### ISSUE THREAD

**Issue by nejch** [tomasbjerre/violations-command-line#2]
It'd be great if the CLI could read a config file to make it easier to configure several violations sources.

For example, calling something like

```shell
npx violations-command-line -cc gl-code-quality-report.json -pv false \
    -v "CHECKSTYLE" "." ".*checkstyle/main\.xml$" "Checkstyle" \
    -v 'YAMLLINT' '.' '.*yamllint/yamllint\.txt$' 'YAMLLint'
```

Would just be called `npx violations-command-line` with a config file like `.violations.yml`:

```yaml
code_climate: gl-code-quality-report.json
print_violations: false
violations:
  - checkstyle:
      folder: .
      pattern: '.*checkstyle/main\.xml'
      name: checkstyle
  - yamllint:
      folder: .
      pattern: '.*yamllint/yamllint\.txt$'
      name: YAMLLint
```

Alternatively if you set up some sane defaults for each analyzer, something like:

```yaml
code_climate: gl-code-quality-report.json
print_violations: false
violations:
  - checkstyle
  - yamllint
```

(unsure if a yaml hash or array should be used for `violations:`, just an idea right now. The yaml might also need some escaping for strings with regexes)

Additionally a `--config-file` flag would help people reuse a config file between projects (e.g. in a submodule shared between repos etc)

For context, see discussions in https://gitlab.com/gitlab-org/gitlab/-/issues/329547#note_612185291.

I think your library could work really well as a lightweight approach to gitlab code quality reports (https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) without relying on code-climate docker images. Thanks for the awesome work @tomasbjerre :)
